### ISSUE TITLE
pygpu was configured but could not be imported

### ISSUE THREAD

**Issue by johnbie** [dennybritz/nn-theano#2]
Sorry if this is a trivial problem!!! I am new to linux environment as a whole and running into problems left and right!!

I'm trying to run gputest.py, but I have been unable to run with GPU. I got it running via CPU, but couldn't get further than that.

I exported following flag:
export THEANO_FLAGS=mode=FAST_RUN,device=cuda,floatX=float32

ran python gputest.py

and got following output:
ERROR (theano.sandbox.gpuarray): pygpu was configured but could not be imported
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/gpuarray/**init**.py", line 20, in <module>
    import pygpu
ImportError: No module named pygpu
[Elemwise{exp,no_inplace}(<TensorType(float32, vector)>)]
Looping 100 times took 2.73069596291 seconds
Result is [ 1.23178029  1.61879337  1.52278066 ...,  2.20771813  2.29967761
  1.62323284]
Used the cpu.

Other informations:
All the packages are running the latest versions from what I know.
There has been hash security issue when attempting to install CUDA.
Ran the code using python 2.7.
For some reason I don't have the CUDA folder in /usr/local.
I have anaconda for python 2.x and python 3.x.
I may have installed CUDA from both nvidia and apt-get. 

Please tell me if there's any more information I need to provide.

**Comment by dennybritz** [comment]
I haven't seen this before, sorry. This seems like a Theano installation issue, not an issue with this code, so I'd recommend asking in the Theano repo (https://github.com/Theano) or on Stackoverflow.
